"""initial schema

Revision ID: ceafc89444aa
Revises: 
Create Date: 2026-09-09 09:29:24.442484
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ceafc89444aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_status'), ['status'], unique=False)
        batch_op.create_index('ix_downloads_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_user_id'))
        batch_op.drop_index('ix_downloads_user_created')
        batch_op.drop_index(batch_op.f('ix_downloads_status'))
        batch_op.drop_index(batch_op.f('ix_downloads_platform'))
        batch_op.drop_index(batch_op.f('ix_downloads_created_at'))

    op.drop_table('downloads')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
